// (C) 2023 uchicom
package com.uchicom.pj.enumeration;

public enum Config {
  SECRET,
  ZONE_ID,
  ZONE_OFFSET,
  SALT_SUFFIX,
  HTTP_ONLY,
  COOKIE_SECURE,
  REFRESH_TOKEN_SALT,
  REFRESH_TOKEN_MAX_AGE_DAYS,
  ACCESS_TOKEN_KEY,
  REFRESH_TOKEN_KEY,
  TOKEN_EXPIRE_MINUTES,
  REFRESH_INTERVAL_MINUTES
}
