name: Create a package

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup reviewdog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest
    - name: Package with Maven And ReviewDog
      env:
        TZ: 'Asia/Tokyo'
        CI_PULL_REQUEST: ${{ github.event.pull_request.number }}
        CI_COMMIT: ${{ github.sha }}
        CI_REPO_OWNER: ${{ github.repository_owner }}
        CI_REPO_NAME: ${{ github.event.repository.name }}
        CI_BRANCH: ${{ github.head_ref }}
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mvn -B package --file pom.xml |& reviewdog -efm='%W[WARNING] %f:[%l,%c] %m' -efm='%C   %m' -efm='%Z  %m' -name=ErrorProne -reporter=github-pr-review -filter-mode=nofilter -fail-on-error=true
